credentials:
  usernames:
    admin:
      email: admin@topoguias.es
      name: Administrador
      password: $2b$12$VQ2Zl7c8qKX5K5Z5Z5Z5ZOuX5X5X5X5X5X5X5X5X5X5X5X5X5X5XO
    usuario1:
      email: usuario1@example.com
      name: Usuario Demo
      password: $2b$12$VQ2Zl7c8qKX5K5Z5Z5Z5ZOuX5X5X5X5X5X5X5X5X5X5X5X5X5X5XO
    
cookie:
  expiry_days: 30
  key: cambiar_esta_clave_por_una_unica_y_segura_en_produccion_12345678
  name: topoguias_auth_cookie

preauthorized:
  emails:
  - nuevousuario@example.com
